<?php /** @var Bss\FAQs\Block\Category\Category $block */ ?>
<div class="faq-category">
    <h2 class="faqcat-title first-title"><i></i>
        <img
            src="<?php echo !empty($block->getFaqCategoryIcon()) ? $block->getFaqCategoryIcon() : $block
                ->getViewFileUrl('Bss_FAQs::images/faq81x81.png'); ?>"/><?php echo __($block->getFaqCategoryTitle()); ?>
        - <?php echo __('FAQs'); ?></h2>
    <?php if ($block->getFaqsList()): ?>
        <ol class="items faqs-list">
            <?php foreach ($block->getFaqsList() as $faq): ?>
                <li class="item" id="faq-id-<?php echo $faq['id']; ?>">
                    <a href="<?php echo $block->getFaqFullPath($faq['id']); ?>">
                        <span class="faq-iconplus"></span><?php echo $faq['title']; ?>
                    </a>
                    <div class="description" id="description">
                        <?php echo $faq['answer']; ?>
                    </div>
                    <div class="read-more"><?php echo __('Read more'); ?></div>
                </li>
            <?php endforeach; ?>
        </ol>
    <?php else: ?>
        <ol class="items faqs-list">
            <li class="item no-question">
                <a href="#"><?php echo __('There are no FAQs was found.'); ?></a>
            </li>
        </ol>
    <?php endif; ?>
</div>
